// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/deployctl/v1/deployctl.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	ComposePath   string                 `protobuf:"bytes,4,opt,name=compose_path,json=composePath,proto3" json:"compose_path,omitempty"`
	EnvPath       string                 `protobuf:"bytes,5,opt,name=env_path,json=envPath,proto3" json:"env_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Deployment) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Deployment) GetComposePath() string {
	if x != nil {
		return x.ComposePath
	}
	return ""
}

func (x *Deployment) GetEnvPath() string {
	if x != nil {
		return x.EnvPath
	}
	return ""
}

type CreateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ComposeFile   string                 `protobuf:"bytes,3,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"`
	EnvFile       string                 `protobuf:"bytes,4,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentRequest) Reset() {
	*x = CreateDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentRequest) ProtoMessage() {}

func (x *CreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeploymentRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *CreateDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeploymentRequest) GetComposeFile() string {
	if x != nil {
		return x.ComposeFile
	}
	return ""
}

func (x *CreateDeploymentRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

type GetDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentRequest) Reset() {
	*x = GetDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentRequest) ProtoMessage() {}

func (x *GetDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDeploymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsRequest) Reset() {
	*x = ListDeploymentsRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsRequest) ProtoMessage() {}

func (x *ListDeploymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsRequest.ProtoReflect.Descriptor instead.
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{3}
}

type ListDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeploymentsResponse) Reset() {
	*x = ListDeploymentsResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResponse) ProtoMessage() {}

func (x *ListDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type DeleteDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentRequest) Reset() {
	*x = DeleteDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentRequest) ProtoMessage() {}

func (x *DeleteDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDeploymentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UpdateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Build         bool                   `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeploymentRequest) Reset() {
	*x = UpdateDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeploymentRequest) ProtoMessage() {}

func (x *UpdateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeploymentRequest) GetBuild() bool {
	if x != nil {
		return x.Build
	}
	return false
}

type DeployDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Build         bool                   `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployDeploymentRequest) Reset() {
	*x = DeployDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDeploymentRequest) ProtoMessage() {}

func (x *DeployDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeployDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{7}
}

func (x *DeployDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployDeploymentRequest) GetBuild() bool {
	if x != nil {
		return x.Build
	}
	return false
}

type RestartDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Build         bool                   `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDeploymentRequest) Reset() {
	*x = RestartDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDeploymentRequest) ProtoMessage() {}

func (x *RestartDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RestartDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{8}
}

func (x *RestartDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestartDeploymentRequest) GetBuild() bool {
	if x != nil {
		return x.Build
	}
	return false
}

type StopDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDeploymentRequest) Reset() {
	*x = StopDeploymentRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDeploymentRequest) ProtoMessage() {}

func (x *StopDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDeploymentRequest.ProtoReflect.Descriptor instead.
func (*StopDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{9}
}

func (x *StopDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListEnvNamesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	EnvFile        string                 `protobuf:"bytes,2,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEnvNamesRequest) Reset() {
	*x = ListEnvNamesRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvNamesRequest) ProtoMessage() {}

func (x *ListEnvNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvNamesRequest.ProtoReflect.Descriptor instead.
func (*ListEnvNamesRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{10}
}

func (x *ListEnvNamesRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *ListEnvNamesRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

type ListEnvNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvNamesResponse) Reset() {
	*x = ListEnvNamesResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvNamesResponse) ProtoMessage() {}

func (x *ListEnvNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvNamesResponse.ProtoReflect.Descriptor instead.
func (*ListEnvNamesResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{11}
}

func (x *ListEnvNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SetEnvRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Variables      map[string]string      `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvFile        string                 `protobuf:"bytes,3,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetEnvRequest) Reset() {
	*x = SetEnvRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnvRequest) ProtoMessage() {}

func (x *SetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnvRequest.ProtoReflect.Descriptor instead.
func (*SetEnvRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{12}
}

func (x *SetEnvRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *SetEnvRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SetEnvRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

type ImportEnvFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	EnvFile        string                 `protobuf:"bytes,3,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportEnvFileRequest) Reset() {
	*x = ImportEnvFileRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportEnvFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportEnvFileRequest) ProtoMessage() {}

func (x *ImportEnvFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportEnvFileRequest.ProtoReflect.Descriptor instead.
func (*ImportEnvFileRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{13}
}

func (x *ImportEnvFileRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *ImportEnvFileRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ImportEnvFileRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

type UnsetEnvRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Names          []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	EnvFile        string                 `protobuf:"bytes,3,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsetEnvRequest) Reset() {
	*x = UnsetEnvRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetEnvRequest) ProtoMessage() {}

func (x *UnsetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetEnvRequest.ProtoReflect.Descriptor instead.
func (*UnsetEnvRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{14}
}

func (x *UnsetEnvRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *UnsetEnvRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *UnsetEnvRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{15}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DeploymentName string                 `protobuf:"bytes,3,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	StartedAtUnix  int64                  `protobuf:"varint,7,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	FinishedAtUnix int64                  `protobuf:"varint,8,opt,name=finished_at_unix,json=finishedAtUnix,proto3" json:"finished_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{16}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Job) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *Job) GetFinishedAtUnix() int64 {
	if x != nil {
		return x.FinishedAtUnix
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{17}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListJobsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentName string                 `protobuf:"bytes,1,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{18}
}

func (x *ListJobsRequest) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{19}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AfterSequence int64                  `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{20}
}

func (x *WatchJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchJobRequest) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{21}
}

func (x *CancelJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Job           *Job                   `protobuf:"bytes,4,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{22}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *JobEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobEvent) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{23}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{24}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{25}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{26}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{27}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployctl_v1_deployctl_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_deployctl_v1_deployctl_proto_rawDescGZIP(), []int{28}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_api_deployctl_v1_deployctl_proto protoreflect.FileDescriptor

const file_api_deployctl_v1_deployctl_proto_rawDesc = "" +
	"\n" +
	" api/deployctl/v1/deployctl.proto\x12\fdeployctl.v1\"\x8c\x01\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12!\n" +
	"\fcompose_path\x18\x04 \x01(\tR\vcomposePath\x12\x19\n" +
	"\benv_path\x18\x05 \x01(\tR\aenvPath\"\x86\x01\n" +
	"\x17CreateDeploymentRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcompose_file\x18\x03 \x01(\tR\vcomposeFile\x12\x19\n" +
	"\benv_file\x18\x04 \x01(\tR\aenvFile\"*\n" +
	"\x14GetDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16ListDeploymentsRequest\"U\n" +
	"\x17ListDeploymentsResponse\x12:\n" +
	"\vdeployments\x18\x01 \x03(\v2\x18.deployctl.v1.DeploymentR\vdeployments\"C\n" +
	"\x17DeleteDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"C\n" +
	"\x17UpdateDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05build\x18\x02 \x01(\bR\x05build\"C\n" +
	"\x17DeployDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05build\x18\x02 \x01(\bR\x05build\"D\n" +
	"\x18RestartDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05build\x18\x02 \x01(\bR\x05build\"+\n" +
	"\x15StopDeploymentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Y\n" +
	"\x13ListEnvNamesRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12\x19\n" +
	"\benv_file\x18\x02 \x01(\tR\aenvFile\",\n" +
	"\x14ListEnvNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\xdb\x01\n" +
	"\rSetEnvRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12H\n" +
	"\tvariables\x18\x02 \x03(\v2*.deployctl.v1.SetEnvRequest.VariablesEntryR\tvariables\x12\x19\n" +
	"\benv_file\x18\x03 \x01(\tR\aenvFile\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x14ImportEnvFileRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x19\n" +
	"\benv_file\x18\x03 \x01(\tR\aenvFile\"k\n" +
	"\x0fUnsetEnvRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x19\n" +
	"\benv_file\x18\x03 \x01(\tR\aenvFile\"$\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xfa\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12'\n" +
	"\x0fdeployment_name\x18\x03 \x01(\tR\x0edeploymentName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\a \x01(\x03R\rstartedAtUnix\x12(\n" +
	"\x10finished_at_unix\x18\b \x01(\x03R\x0efinishedAtUnix\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fListJobsRequest\x12'\n" +
	"\x0fdeployment_name\x18\x01 \x01(\tR\x0edeploymentName\"9\n" +
	"\x10ListJobsResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.deployctl.v1.JobR\x04jobs\"H\n" +
	"\x0fWatchJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x03R\rafterSequence\"\"\n" +
	"\x10CancelJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"|\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\x03job\x18\x04 \x01(\v2\x11.deployctl.v1.JobR\x03job\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x15\n" +
	"\x13CapabilitiesRequest\":\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities2\xc4\x05\n" +
	"\x11DeploymentService\x12T\n" +
	"\x10CreateDeployment\x12%.deployctl.v1.CreateDeploymentRequest\x1a\x19.deployctl.v1.JobResponse\x12M\n" +
	"\rGetDeployment\x12\".deployctl.v1.GetDeploymentRequest\x1a\x18.deployctl.v1.Deployment\x12^\n" +
	"\x0fListDeployments\x12$.deployctl.v1.ListDeploymentsRequest\x1a%.deployctl.v1.ListDeploymentsResponse\x12T\n" +
	"\x10DeleteDeployment\x12%.deployctl.v1.DeleteDeploymentRequest\x1a\x19.deployctl.v1.JobResponse\x12T\n" +
	"\x10UpdateDeployment\x12%.deployctl.v1.UpdateDeploymentRequest\x1a\x19.deployctl.v1.JobResponse\x12T\n" +
	"\x10DeployDeployment\x12%.deployctl.v1.DeployDeploymentRequest\x1a\x19.deployctl.v1.JobResponse\x12V\n" +
	"\x11RestartDeployment\x12&.deployctl.v1.RestartDeploymentRequest\x1a\x19.deployctl.v1.JobResponse\x12P\n" +
	"\x0eStopDeployment\x12#.deployctl.v1.StopDeploymentRequest\x1a\x19.deployctl.v1.JobResponse2\xbb\x02\n" +
	"\n" +
	"EnvService\x12U\n" +
	"\fListEnvNames\x12!.deployctl.v1.ListEnvNamesRequest\x1a\".deployctl.v1.ListEnvNamesResponse\x12@\n" +
	"\x06SetEnv\x12\x1b.deployctl.v1.SetEnvRequest\x1a\x19.deployctl.v1.JobResponse\x12N\n" +
	"\rImportEnvFile\x12\".deployctl.v1.ImportEnvFileRequest\x1a\x19.deployctl.v1.JobResponse\x12D\n" +
	"\bUnsetEnv\x12\x1d.deployctl.v1.UnsetEnvRequest\x1a\x19.deployctl.v1.JobResponse2\x96\x02\n" +
	"\n" +
	"JobService\x128\n" +
	"\x06GetJob\x12\x1b.deployctl.v1.GetJobRequest\x1a\x11.deployctl.v1.Job\x12I\n" +
	"\bListJobs\x12\x1d.deployctl.v1.ListJobsRequest\x1a\x1e.deployctl.v1.ListJobsResponse\x12C\n" +
	"\bWatchJob\x12\x1d.deployctl.v1.WatchJobRequest\x1a\x16.deployctl.v1.JobEvent0\x01\x12>\n" +
	"\tCancelJob\x12\x1e.deployctl.v1.CancelJobRequest\x1a\x11.deployctl.v1.Job2\xf3\x01\n" +
	"\rSystemService\x12C\n" +
	"\x06Health\x12\x1b.deployctl.v1.HealthRequest\x1a\x1c.deployctl.v1.HealthResponse\x12F\n" +
	"\aVersion\x12\x1c.deployctl.v1.VersionRequest\x1a\x1d.deployctl.v1.VersionResponse\x12U\n" +
	"\fCapabilities\x12!.deployctl.v1.CapabilitiesRequest\x1a\".deployctl.v1.CapabilitiesResponseB\x1cZ\x1adeployctl/internal/rpc;rpcb\x06proto3"

var (
	file_api_deployctl_v1_deployctl_proto_rawDescOnce sync.Once
	file_api_deployctl_v1_deployctl_proto_rawDescData []byte
)

func file_api_deployctl_v1_deployctl_proto_rawDescGZIP() []byte {
	file_api_deployctl_v1_deployctl_proto_rawDescOnce.Do(func() {
		file_api_deployctl_v1_deployctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_deployctl_v1_deployctl_proto_rawDesc), len(file_api_deployctl_v1_deployctl_proto_rawDesc)))
	})
	return file_api_deployctl_v1_deployctl_proto_rawDescData
}

var file_api_deployctl_v1_deployctl_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_deployctl_v1_deployctl_proto_goTypes = []any{
	(*Deployment)(nil),               // 0: deployctl.v1.Deployment
	(*CreateDeploymentRequest)(nil),  // 1: deployctl.v1.CreateDeploymentRequest
	(*GetDeploymentRequest)(nil),     // 2: deployctl.v1.GetDeploymentRequest
	(*ListDeploymentsRequest)(nil),   // 3: deployctl.v1.ListDeploymentsRequest
	(*ListDeploymentsResponse)(nil),  // 4: deployctl.v1.ListDeploymentsResponse
	(*DeleteDeploymentRequest)(nil),  // 5: deployctl.v1.DeleteDeploymentRequest
	(*UpdateDeploymentRequest)(nil),  // 6: deployctl.v1.UpdateDeploymentRequest
	(*DeployDeploymentRequest)(nil),  // 7: deployctl.v1.DeployDeploymentRequest
	(*RestartDeploymentRequest)(nil), // 8: deployctl.v1.RestartDeploymentRequest
	(*StopDeploymentRequest)(nil),    // 9: deployctl.v1.StopDeploymentRequest
	(*ListEnvNamesRequest)(nil),      // 10: deployctl.v1.ListEnvNamesRequest
	(*ListEnvNamesResponse)(nil),     // 11: deployctl.v1.ListEnvNamesResponse
	(*SetEnvRequest)(nil),            // 12: deployctl.v1.SetEnvRequest
	(*ImportEnvFileRequest)(nil),     // 13: deployctl.v1.ImportEnvFileRequest
	(*UnsetEnvRequest)(nil),          // 14: deployctl.v1.UnsetEnvRequest
	(*JobResponse)(nil),              // 15: deployctl.v1.JobResponse
	(*Job)(nil),                      // 16: deployctl.v1.Job
	(*GetJobRequest)(nil),            // 17: deployctl.v1.GetJobRequest
	(*ListJobsRequest)(nil),          // 18: deployctl.v1.ListJobsRequest
	(*ListJobsResponse)(nil),         // 19: deployctl.v1.ListJobsResponse
	(*WatchJobRequest)(nil),          // 20: deployctl.v1.WatchJobRequest
	(*CancelJobRequest)(nil),         // 21: deployctl.v1.CancelJobRequest
	(*JobEvent)(nil),                 // 22: deployctl.v1.JobEvent
	(*HealthRequest)(nil),            // 23: deployctl.v1.HealthRequest
	(*HealthResponse)(nil),           // 24: deployctl.v1.HealthResponse
	(*VersionRequest)(nil),           // 25: deployctl.v1.VersionRequest
	(*VersionResponse)(nil),          // 26: deployctl.v1.VersionResponse
	(*CapabilitiesRequest)(nil),      // 27: deployctl.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),     // 28: deployctl.v1.CapabilitiesResponse
	nil,                              // 29: deployctl.v1.SetEnvRequest.VariablesEntry
}
var file_api_deployctl_v1_deployctl_proto_depIdxs = []int32{
	0,  // 0: deployctl.v1.ListDeploymentsResponse.deployments:type_name -> deployctl.v1.Deployment
	29, // 1: deployctl.v1.SetEnvRequest.variables:type_name -> deployctl.v1.SetEnvRequest.VariablesEntry
	16, // 2: deployctl.v1.ListJobsResponse.jobs:type_name -> deployctl.v1.Job
	16, // 3: deployctl.v1.JobEvent.job:type_name -> deployctl.v1.Job
	1,  // 4: deployctl.v1.DeploymentService.CreateDeployment:input_type -> deployctl.v1.CreateDeploymentRequest
	2,  // 5: deployctl.v1.DeploymentService.GetDeployment:input_type -> deployctl.v1.GetDeploymentRequest
	3,  // 6: deployctl.v1.DeploymentService.ListDeployments:input_type -> deployctl.v1.ListDeploymentsRequest
	5,  // 7: deployctl.v1.DeploymentService.DeleteDeployment:input_type -> deployctl.v1.DeleteDeploymentRequest
	6,  // 8: deployctl.v1.DeploymentService.UpdateDeployment:input_type -> deployctl.v1.UpdateDeploymentRequest
	7,  // 9: deployctl.v1.DeploymentService.DeployDeployment:input_type -> deployctl.v1.DeployDeploymentRequest
	8,  // 10: deployctl.v1.DeploymentService.RestartDeployment:input_type -> deployctl.v1.RestartDeploymentRequest
	9,  // 11: deployctl.v1.DeploymentService.StopDeployment:input_type -> deployctl.v1.StopDeploymentRequest
	10, // 12: deployctl.v1.EnvService.ListEnvNames:input_type -> deployctl.v1.ListEnvNamesRequest
	12, // 13: deployctl.v1.EnvService.SetEnv:input_type -> deployctl.v1.SetEnvRequest
	13, // 14: deployctl.v1.EnvService.ImportEnvFile:input_type -> deployctl.v1.ImportEnvFileRequest
	14, // 15: deployctl.v1.EnvService.UnsetEnv:input_type -> deployctl.v1.UnsetEnvRequest
	17, // 16: deployctl.v1.JobService.GetJob:input_type -> deployctl.v1.GetJobRequest
	18, // 17: deployctl.v1.JobService.ListJobs:input_type -> deployctl.v1.ListJobsRequest
	20, // 18: deployctl.v1.JobService.WatchJob:input_type -> deployctl.v1.WatchJobRequest
	21, // 19: deployctl.v1.JobService.CancelJob:input_type -> deployctl.v1.CancelJobRequest
	23, // 20: deployctl.v1.SystemService.Health:input_type -> deployctl.v1.HealthRequest
	25, // 21: deployctl.v1.SystemService.Version:input_type -> deployctl.v1.VersionRequest
	27, // 22: deployctl.v1.SystemService.Capabilities:input_type -> deployctl.v1.CapabilitiesRequest
	15, // 23: deployctl.v1.DeploymentService.CreateDeployment:output_type -> deployctl.v1.JobResponse
	0,  // 24: deployctl.v1.DeploymentService.GetDeployment:output_type -> deployctl.v1.Deployment
	4,  // 25: deployctl.v1.DeploymentService.ListDeployments:output_type -> deployctl.v1.ListDeploymentsResponse
	15, // 26: deployctl.v1.DeploymentService.DeleteDeployment:output_type -> deployctl.v1.JobResponse
	15, // 27: deployctl.v1.DeploymentService.UpdateDeployment:output_type -> deployctl.v1.JobResponse
	15, // 28: deployctl.v1.DeploymentService.DeployDeployment:output_type -> deployctl.v1.JobResponse
	15, // 29: deployctl.v1.DeploymentService.RestartDeployment:output_type -> deployctl.v1.JobResponse
	15, // 30: deployctl.v1.DeploymentService.StopDeployment:output_type -> deployctl.v1.JobResponse
	11, // 31: deployctl.v1.EnvService.ListEnvNames:output_type -> deployctl.v1.ListEnvNamesResponse
	15, // 32: deployctl.v1.EnvService.SetEnv:output_type -> deployctl.v1.JobResponse
	15, // 33: deployctl.v1.EnvService.ImportEnvFile:output_type -> deployctl.v1.JobResponse
	15, // 34: deployctl.v1.EnvService.UnsetEnv:output_type -> deployctl.v1.JobResponse
	16, // 35: deployctl.v1.JobService.GetJob:output_type -> deployctl.v1.Job
	19, // 36: deployctl.v1.JobService.ListJobs:output_type -> deployctl.v1.ListJobsResponse
	22, // 37: deployctl.v1.JobService.WatchJob:output_type -> deployctl.v1.JobEvent
	16, // 38: deployctl.v1.JobService.CancelJob:output_type -> deployctl.v1.Job
	24, // 39: deployctl.v1.SystemService.Health:output_type -> deployctl.v1.HealthResponse
	26, // 40: deployctl.v1.SystemService.Version:output_type -> deployctl.v1.VersionResponse
	28, // 41: deployctl.v1.SystemService.Capabilities:output_type -> deployctl.v1.CapabilitiesResponse
	23, // [23:42] is the sub-list for method output_type
	4,  // [4:23] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_deployctl_v1_deployctl_proto_init() }
func file_api_deployctl_v1_deployctl_proto_init() {
	if File_api_deployctl_v1_deployctl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_deployctl_v1_deployctl_proto_rawDesc), len(file_api_deployctl_v1_deployctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_deployctl_v1_deployctl_proto_goTypes,
		DependencyIndexes: file_api_deployctl_v1_deployctl_proto_depIdxs,
		MessageInfos:      file_api_deployctl_v1_deployctl_proto_msgTypes,
	}.Build()
	File_api_deployctl_v1_deployctl_proto = out.File
	file_api_deployctl_v1_deployctl_proto_goTypes = nil
	file_api_deployctl_v1_deployctl_proto_depIdxs = nil
}
